require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InboundEmailsController do

  # This should return the minimal set of attributes required to create a valid
  # InboundEmail. As you add validations to InboundEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "text" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InboundEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inbound_emails as @inbound_emails" do
      inbound_email = InboundEmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inbound_emails).should eq([inbound_email])
    end
  end

  describe "GET show" do
    it "assigns the requested inbound_email as @inbound_email" do
      inbound_email = InboundEmail.create! valid_attributes
      get :show, {:id => inbound_email.to_param}, valid_session
      assigns(:inbound_email).should eq(inbound_email)
    end
  end

  describe "GET new" do
    it "assigns a new inbound_email as @inbound_email" do
      get :new, {}, valid_session
      assigns(:inbound_email).should be_a_new(InboundEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested inbound_email as @inbound_email" do
      inbound_email = InboundEmail.create! valid_attributes
      get :edit, {:id => inbound_email.to_param}, valid_session
      assigns(:inbound_email).should eq(inbound_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InboundEmail" do
        expect {
          post :create, {:inbound_email => valid_attributes}, valid_session
        }.to change(InboundEmail, :count).by(1)
      end

      it "assigns a newly created inbound_email as @inbound_email" do
        post :create, {:inbound_email => valid_attributes}, valid_session
        assigns(:inbound_email).should be_a(InboundEmail)
        assigns(:inbound_email).should be_persisted
      end

      it "redirects to the created inbound_email" do
        post :create, {:inbound_email => valid_attributes}, valid_session
        response.should redirect_to(InboundEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inbound_email as @inbound_email" do
        # Trigger the behavior that occurs when invalid params are submitted
        InboundEmail.any_instance.stub(:save).and_return(false)
        post :create, {:inbound_email => { "text" => "invalid value" }}, valid_session
        assigns(:inbound_email).should be_a_new(InboundEmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InboundEmail.any_instance.stub(:save).and_return(false)
        post :create, {:inbound_email => { "text" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inbound_email" do
        inbound_email = InboundEmail.create! valid_attributes
        # Assuming there are no other inbound_emails in the database, this
        # specifies that the InboundEmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InboundEmail.any_instance.should_receive(:update).with({ "text" => "MyText" })
        put :update, {:id => inbound_email.to_param, :inbound_email => { "text" => "MyText" }}, valid_session
      end

      it "assigns the requested inbound_email as @inbound_email" do
        inbound_email = InboundEmail.create! valid_attributes
        put :update, {:id => inbound_email.to_param, :inbound_email => valid_attributes}, valid_session
        assigns(:inbound_email).should eq(inbound_email)
      end

      it "redirects to the inbound_email" do
        inbound_email = InboundEmail.create! valid_attributes
        put :update, {:id => inbound_email.to_param, :inbound_email => valid_attributes}, valid_session
        response.should redirect_to(inbound_email)
      end
    end

    describe "with invalid params" do
      it "assigns the inbound_email as @inbound_email" do
        inbound_email = InboundEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InboundEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => inbound_email.to_param, :inbound_email => { "text" => "invalid value" }}, valid_session
        assigns(:inbound_email).should eq(inbound_email)
      end

      it "re-renders the 'edit' template" do
        inbound_email = InboundEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InboundEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => inbound_email.to_param, :inbound_email => { "text" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inbound_email" do
      inbound_email = InboundEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => inbound_email.to_param}, valid_session
      }.to change(InboundEmail, :count).by(-1)
    end

    it "redirects to the inbound_emails list" do
      inbound_email = InboundEmail.create! valid_attributes
      delete :destroy, {:id => inbound_email.to_param}, valid_session
      response.should redirect_to(inbound_emails_url)
    end
  end

end
